[build]
  command = """
  # Install Swift 6.0
  wget https://download.swift.org/swift-6.0-release/ubuntu2204/swift-6.0-RELEASE/swift-6.0-RELEASE-ubuntu22.04.tar.gz
  tar -xvzf swift-6.0-RELEASE-ubuntu22.04.tar.gz
  export PATH=$PWD/swift-6.0-RELEASE-ubuntu22.04/usr/bin:$PATH
  
  # Verify Swift installation
  swift --version
  
  # Build and run the Publish project
  swift package reset
  swift package update
  swift build -c release
  swift run --configuration release Publish run
  """
  publish = "Output/"

[build.environment]
  SWIFT_VERSION = "6.0"

[context.production.environment]
  SWIFT_VERSION = "6.0"
