[build]
  command = "swift build"
  environment = { SWIFT_VERSION = "5.8" }

[context.production]
  environment = { SWIFT_VERSION = "5.8" }

  command = """
  export SWIFT_VERSION=5.8
  curl -s https://download.swift.org/swift-${SWIFT_VERSION}-release/ubuntu2004/swift-${SWIFT_VERSION}-RELEASE/swift-${SWIFT_VERSION}-RELEASE-ubuntu20.04.tar.gz | tar -xz
  export PATH=$(pwd)/swift-${SWIFT_VERSION}-RELEASE-ubuntu20.04/usr/bin:$PATH
  swift package clean && swift build --disable-sandbox && swift run
  """
  publish = "Output/"
