[build]
  command = """
  swift package update
  swift build -c release --product Publish
  .build/release/Publish run
  """
  publish = "Output/"

[build.environment]
  SWIFT_VERSION = "6.0"

[context.production.environment]
  SWIFT_VERSION = "6.0"
