[build]
  command = """
  wget https://download.swift.org/swift-5.8-release/ubuntu2204/swift-5.8-RELEASE/swift-5.8-RELEASE-ubuntu22.04.tar.gz
  tar -xvzf swift-5.8-RELEASE-ubuntu22.04.tar.gz || tar -xvf swift-5.8-RELEASE-ubuntu22.04.tar
  export PATH=$PWD/swift-5.8-RELEASE-ubuntu22.04/usr/bin:$PATH
  swift --version
  """
  environment = { SWIFT_VERSION = "5.8" }

[context.production]
  environment = { SWIFT_VERSION = "5.8" }
  publish = "Output/"
