[build]
  command = """
  swift package update
  swift build -c release
  swift run publish run
  """
  publish = "Output/"

[build.environment]
  SWIFT_VERSION = "6.0"

[context.production.environment]
  SWIFT_VERSION = "6.0"
