name: Deploy Publish Site

on:
  push:
    branches:
      - main  # Trigger on the main branch

jobs:
  deploy:
    runs-on: macos-latest  # macOS is required for Swift

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Swift
        run: swift --version  # Verify Swift installation

      - name: Build Site
        run: |
          mkdir -p Output  # Ensure Output/ exists
          swift run || { echo "❌ Swift build failed!"; exit 1; }  # Fail the job if Swift build fails
          ls -lah  # Check the root directory
          ls -lah Output || { echo "❌ Output folder is missing!"; exit 1; }  # Fail if Output is missing

      - name: Verify Output Folder
        run: |
          if [ -d "./Output" ]; then
            echo "✅ Output folder exists."
          else
            echo "❌ Output folder is missing!"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}  # Use the custom PAT secret
          publish_branch: gh-pages  # Deploy to gh-pages instead of main
          publish_dir: ./Output
          keep_files: true  # Prevents deleting existing files
