name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: macos-latest  # macOS is required for Swift

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          clean: true  # Ensures the repository is cleaned before checking out

      - name: Configure Git
        run: |
          git config --global user.name "Rahul Bandal"
          git config --global user.email "bandalrahul@yahoo.com"

      - name: Install Swift
        run: swift --version  # Verify Swift installation

      - name: Build the site
        run: |
          mkdir -p Output  # Ensure Output directory exists
          echo "Building the site with Swift..."
          swift run || { echo "❌ Swift build failed!"; exit 1; }  # Fail the job if Swift build fails
          ls -lah  # List the root directory contents
          ls -lah Output || { echo "❌ Output folder is missing!"; exit 1; }  # Verify Output folder

      - name: Verify Output Folder Exists
        run: |
          if [ -d "./Output" ]; then
            echo "✅ Output folder exists."
          else
            echo "❌ Output folder is missing!"
            exit 1
          fi

      - name: List Output Directory Contents
        run: ls -lah ./Output  # Ensure the Output folder contains files

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./Output  # Path to the folder you want to upload

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ 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 }}  # Automatically available in GitHub Actions
          publish_branch: gh-pages  # Deploy to the gh-pages branch
          publish_dir: ./Output  # Deploy the contents of the Output folder
          keep_files: true  # Prevents deleting existing files in the gh-pages branch
