name: Deploy Publish Site

on:
  push:
    branches:
      - main  # Change to your desired branch

jobs:
  deploy:
    runs-on: macos-latest  # macOS is required for Swift

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Swift
        run: swift --version  # Verify Swift installation

      - name: Build Site
        run: |
          mkdir -p Output  # Ensure Output/ folder exists
          swift run || echo "❌ Swift build failed!"
          ls -lah  # Check the root directory
          ls -lah Output || echo "❌ Output folder is missing!"

      - name: Find Output Folder
        run: find . -type d -name "Output"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main  # Use 'main' instead of 'gh-pages'
          publish_dir: ./Output
          keep_files: true
