name: Deploy Publish Site

on:
  push:
    branches:
      - main  # Adjust if using a different branch

jobs:
  deploy:
    runs-on: macos-latest  # macOS is needed for Swift

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Swift
        run: |
          swift --version  # Verify Swift installation

      - name: Build Site
        run: |
          swift run  # This generates the site in Output/
          ls -l  # Check if Output/ is created

      - name: Debug Output Folder
        run: ls -lah
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: ./Output  # Deploy directly from Output/
